'''
Revision ID: 002_add_email_verified
Revises: 001_initial
Create Date: 2026-06-08 17:45
'''

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "002_add_email_verified"
down_revision = "001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
