"use client";

import React, { useState, useEffect } from "react";
import { 
  PhoneCall, 
  Search, 
  Loader2, 
  AlertCircle, 
  Play, 
  FileText, 
  MessageSquare,
  Clock,
  ArrowUpRight,
  ChevronRight,
  Volume2,
  Calendar,
  X
} from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/UI/Card";
import { Button } from "@/components/UI/Button";
import { getCallLogs, type CallLog } from "@/lib/api";

export default function CallLogsPage() {
  const [logs, setLogs] = useState<CallLog[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [error, setError] = useState<string | null>(null);

  // Selected call log detail modal
  const [selectedLog, setSelectedLog] = useState<CallLog | null>(null);

  useEffect(() => {
    loadCallLogs();
    
    // Poll for call updates every 7 seconds while viewing call history (useful for live calls)
    const interval = setInterval(loadCallLogsSilent, 7000);
    return () => clearInterval(interval);
  }, []);

  const loadCallLogs = async () => {
    try {
      setLoading(true);
      const data = await getCallLogs();
      setLogs(data);
    } catch (err: any) {
      setError(err.message || "Failed to load call history logs");
    } finally {
      setLoading(false);
    }
  };

  const loadCallLogsSilent = async () => {
    try {
      const data = await getCallLogs();
      setLogs(data);
      // Update selected log reference if it is open in modal to show live updates (like transcript)
      setSelectedLog((curr) => {
        if (!curr) return null;
        const updated = data.find(item => item.id === curr.id);
        return updated || curr;
      });
    } catch {
      // ignore silent fetch failures
    }
  };

  // Format duration in seconds to M:SS
  const formatDuration = (sec: number) => {
    if (!sec) return "0s";
    const minutes = Math.floor(sec / 60);
    const seconds = sec % 60;
    return minutes > 0 ? `${minutes}m ${seconds}s` : `${seconds}s`;
  };

  // Format timestamp nicely
  const formatDateTime = (dateStr?: string) => {
    if (!dateStr) return "—";
    const date = new Date(dateStr);
    return date.toLocaleString(undefined, {
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true
    });
  };

  // Parse raw text transcripts into message bubble lists
  // Vapi sends transcript as "Agent: Hello\nUser: Hi there\nAgent: How can I help?"
  const parseTranscript = (text?: string) => {
    if (!text) return [];
    
    // If it has line breaks, split by line and parse
    const lines = text.split('\n');
    const parsed: Array<{ role: 'agent' | 'user' | 'system'; content: string }> = [];
    
    lines.forEach(line => {
      const trimmed = line.trim();
      if (!trimmed) return;
      
      const lower = trimmed.toLowerCase();
      if (lower.startsWith('agent:') || lower.startsWith('assistant:')) {
        const content = trimmed.substring(trimmed.indexOf(':') + 1).trim();
        parsed.push({ role: 'agent', content });
      } else if (lower.startsWith('user:') || lower.startsWith('customer:') || lower.startsWith('parent:')) {
        const content = trimmed.substring(trimmed.indexOf(':') + 1).trim();
        parsed.push({ role: 'user', content });
      } else {
        // Fallback try to detect from the text or label it user/agent
        parsed.push({ role: 'user', content: trimmed });
      }
    });

    return parsed;
  };

  // Filter logs based on query
  const filteredLogs = logs.filter((log) => {
    const term = searchQuery.toLowerCase();
    const contactName = log.contact_name || log.contacts?.name || "";
    const campaignName = log.campaigns?.name || "";
    return (
      contactName.toLowerCase().includes(term) ||
      log.contact_phone.includes(term) ||
      campaignName.toLowerCase().includes(term) ||
      log.status.toLowerCase().includes(term)
    );
  });

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-2">
            <PhoneCall className="h-6 w-6 text-violet-400" />
            Outbound Call History
          </h1>
          <p className="text-gray-400 text-sm">
            Review detailed conversation logs, audio recordings, and summaries generated by AI agents.
          </p>
        </div>
        
        <Button variant="outline" size="sm" onClick={loadCallLogs} className="h-10">
          Refresh List
        </Button>
      </div>

      {/* Error notification */}
      {error && (
        <div className="p-4 rounded-xl bg-red-500/10 border border-red-500/20 text-red-400 flex items-start gap-3">
          <AlertCircle className="h-5 w-5 shrink-0 mt-0.5" />
          <p className="text-sm">{error}</p>
        </div>
      )}

      {/* Main Table Card */}
      <Card className="!p-0 overflow-hidden">
        <div className="p-5 border-b border-white/[0.08]/60 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="relative w-full sm:max-w-xs">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-500" />
            <input
              type="text"
              placeholder="Search by contact, phone, campaign..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-4 py-2 bg-zinc-950 border border-white/[0.08]/80 rounded-lg text-sm text-white placeholder-zinc-500 focus:outline-none focus:ring-1 focus:ring-indigo-500/50"
            />
          </div>
          
          <div className="text-xs text-gray-500 font-medium">
            Total {filteredLogs.length} calls logged
          </div>
        </div>

        {loading ? (
          <div className="flex flex-col items-center justify-center py-20 gap-3">
            <Loader2 className="h-8 w-8 text-violet-400 animate-spin" />
            <p className="text-gray-400 text-sm">Loading call registry...</p>
          </div>
        ) : filteredLogs.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 px-4 text-center">
            <div className="p-3 rounded-2xl bg-zinc-800/30 border border-white/[0.08]/50 mb-4 text-gray-500">
              <PhoneCall className="h-6 w-6" />
            </div>
            <h3 className="text-base font-semibold text-white">No calls logged</h3>
            <p className="text-xs text-gray-500 mt-1 max-w-xs mx-auto">
              {searchQuery ? "No logs match your filters." : "Start an outbound campaign to record call logs here."}
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-sm">
              <thead>
                <tr className="border-b border-white/[0.08] bg-zinc-900/30 text-gray-400 uppercase font-semibold text-xs tracking-wider">
                  <th className="px-6 py-4">Contact</th>
                  <th className="px-6 py-4">Campaign</th>
                  <th className="px-6 py-4">Status</th>
                  <th className="px-6 py-4">Duration</th>
                  <th className="px-6 py-4">Call Time</th>
                  <th className="px-6 py-4 text-right">Details</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-850/30 text-gray-300">
                {filteredLogs.map((log) => {
                  const contactName = log.contact_name || log.contacts?.name || "Unknown";
                  const campaignName = log.campaigns?.name || "Direct Dial";
                  return (
                    <tr 
                      key={log.id} 
                      onClick={() => setSelectedLog(log)}
                      className="hover:bg-zinc-800/10 transition-colors duration-150 cursor-pointer"
                    >
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-1.5">
                          <p className="font-semibold text-white">{contactName}</p>
                          {log.vapi_call_id?.startsWith('sim_') && (
                            <span className="text-[8px] bg-amber-500/10 text-amber-400 border border-amber-500/20 px-1 py-0.2 rounded font-bold uppercase tracking-wider">
                              SIM
                            </span>
                          )}
                        </div>
                        <p className="text-xs text-gray-500">{log.contact_phone}</p>
                      </td>
                      <td className="px-6 py-4 text-gray-400 font-medium">{campaignName}</td>
                      <td className="px-6 py-4">
                        <span className={`px-2 py-0.5 rounded text-[9px] font-bold uppercase tracking-wide border ${
                          log.status === 'completed' 
                            ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-400"
                            : log.status === 'calling'
                            ? "bg-amber-500/10 border-amber-500/20 text-amber-400 animate-pulse"
                            : log.status === 'failed'
                            ? "bg-rose-500/10 border-rose-500/20 text-rose-400"
                            : log.status === 'busy' || log.status === 'no-answer'
                            ? "bg-[#1F2937] border-white/[0.08] text-gray-400"
                            : "bg-violet-500/10 border-violet-500/20 text-violet-400"
                        }`}>
                          {log.status}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-gray-400 flex items-center gap-1.5 mt-2.5">
                        <Clock className="h-3.5 w-3.5 text-gray-600" />
                        {formatDuration(log.duration)}
                      </td>
                      <td className="px-6 py-4 text-gray-500 text-xs">{formatDateTime(log.created_at)}</td>
                      <td className="px-6 py-4 text-right">
                        <ChevronRight className="h-4 w-4 text-gray-600 inline-block hover:text-gray-300" />
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </Card>

      {/* Detail Modal Overlay */}
      {selectedLog && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4">
          <Card className="w-full max-w-2xl flex flex-col max-h-[90vh]">
            <CardHeader className="flex flex-row items-center justify-between pb-3 border-b border-zinc-850">
              <div>
                <CardTitle className="text-lg flex items-center gap-2">
                  Call Log Explorer: {selectedLog.contact_name || selectedLog.contacts?.name || "Unknown"}
                  {selectedLog.vapi_call_id?.startsWith('sim_') && (
                    <span className="text-[10px] bg-amber-500/10 text-amber-400 border border-amber-500/20 px-2 py-0.5 rounded font-bold uppercase tracking-wider">
                      Simulated
                    </span>
                  )}
                </CardTitle>
                <CardDescription className="flex items-center gap-4 mt-1">
                  <span className="flex items-center gap-1 text-xs">
                    <Calendar className="h-3.5 w-3.5" />
                    {formatDateTime(selectedLog.created_at)}
                  </span>
                  <span className="flex items-center gap-1 text-xs">
                    <Clock className="h-3.5 w-3.5" />
                    Duration: {formatDuration(selectedLog.duration)}
                  </span>
                </CardDescription>
              </div>
              <button onClick={() => setSelectedLog(null)} className="text-gray-500 hover:text-white">
                <X className="h-5 w-5" />
              </button>
            </CardHeader>
            
            <div className="flex-1 overflow-y-auto p-6 space-y-6">
              {/* Call Recording Playback */}
              {selectedLog.recording_url && (
                <div className="p-4 rounded-xl border border-violet-500/25 bg-violet-500/5 space-y-2.5">
                  <span className="text-xs font-bold text-indigo-300 flex items-center gap-1.5">
                    <Volume2 className="h-4 w-4" />
                    Call Voice Recording Playback
                  </span>
                  <audio 
                    src={selectedLog.recording_url} 
                    controls 
                    className="w-full accent-indigo-600 bg-transparent"
                  />
                </div>
              )}

              {/* Call Summary Notes */}
              {selectedLog.summary && (
                <div className="space-y-2">
                  <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider flex items-center gap-1.5">
                    <FileText className="h-3.5 w-3.5" />
                    AI Call Summary
                  </h3>
                  <div className="p-4 rounded-xl border border-zinc-850 bg-zinc-950/60 leading-relaxed text-sm text-gray-300 font-medium">
                    {selectedLog.summary}
                  </div>
                </div>
              )}

              {/* Structured Transcription dialogues */}
              <div className="space-y-3">
                <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider flex items-center gap-1.5">
                  <MessageSquare className="h-3.5 w-3.5" />
                  Conversation Transcript
                </h3>
                
                {!selectedLog.transcript ? (
                  <div className="p-6 text-center text-xs text-gray-600 italic border border-zinc-850 rounded-xl">
                    {selectedLog.status === 'calling' 
                      ? "Transcription will stream in when call ends..." 
                      : "No transcription text recorded for this call."}
                  </div>
                ) : (
                  <div className="space-y-3 bg-zinc-950/50 p-4 rounded-xl border border-zinc-850 max-h-[350px] overflow-y-auto">
                    {parseTranscript(selectedLog.transcript).map((msg, index) => {
                      const isAgent = msg.role === 'agent';
                      return (
                        <div 
                          key={index}
                          className={`flex flex-col ${isAgent ? "items-start" : "items-end"}`}
                        >
                          <div className={`text-[10px] font-bold text-gray-500 mb-1 ${isAgent ? "pl-2" : "pr-2"}`}>
                            {isAgent ? "AI Voice Agent" : "Customer / Parent"}
                          </div>
                          <div className={`p-3 rounded-2xl max-w-[85%] text-xs leading-relaxed ${
                            isAgent 
                              ? "bg-[#1F2937] text-zinc-100 rounded-tl-none border border-white/[0.08]/40" 
                              : "bg-violet-600/90 text-white rounded-tr-none shadow-sm shadow-indigo-600/10"
                          }`}>
                            {msg.content}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            </div>

            <div className="p-6 border-t border-zinc-850 flex justify-end bg-zinc-900/20">
              <Button size="sm" onClick={() => setSelectedLog(null)}>
                Close Explorer
              </Button>
            </div>
          </Card>
        </div>
      )}
    </div>
  );
}
